language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: dBdFrtF4HOKAegiHLUxmYYp1CwNwz/U44kxKhuDAW2zGfVX3aoeYoGPB3uvn5RBTY3zYRuhPK3LYo7G2Cb6HUaev5uxWzoelT1yk1vVCDgGr/Ll/VVDt7A471SbfI/Wb0AXhFpDAsikEj7NgRK/BrWo4BoWd3V7h00z0GwjkBoZzUn9B5L5VFASypFwMhckJGjdB2EnY/9HRrTPVf47GODZ299H/nBPZBaibrZuLspg+79yL79cA8+eX3uNuiBxrrkqKzt2vkOIydPq4i4nRbYcwdIHL4vJXFgOWkyEJWZqUsfMEk5O20l+oPcT69MC37DNcO4NhqvBxcDJUxr5+bD5aNXpzWI4ikXM+78Xy+XYIL6XakXL7ERP+LSRcU/r3solxpAd+PapHHQ87rj1hr305JLilPRHuUX4FClqaV2t+h9aaxWjIimea//YG2TXeqTrQqsIegCJLn2ro7AGRwgO0JYkYmCTIPvWLjoucrrKaReFDMwHntj7ZWG7aQKtTXRilD+GUYWt/xek0XM6QLUaeXWxLYAdfYWpVpiJIzilc0HBhGQv5msIEAVnzxTk+umq/iyq07E5BxHNoTTbqHHNPeLZ0quxxiYLWis+ELn+UTA/VUX5JvdrmbyQ2n7jqFESSaEX0pIXUh3UhMWOnWNbivCw6lGfEdxDnxP7N1j8=
notifications:
  slack:
    secure: gDlIwKWtdEq9lN9uZy0xmY+arJP+Bqvw1KXjYSs9EOxGY/R8AVYYUmX/YK05APijFmp41siD9Qd0uvLL7KSy4JvB0UXh7UQfQRF3QGv0HFJ2+KISbX7Ta0BPeHq4I3U5vcFQZGlw9JDG5d/0q2ofaNFt7nhGdIcn+noiYt5Q989FK0/MuKEMVAsH1mjBYcx/3vXSKQgomJfDjqSLTr97fgXYBFCrANaf3kYBmns3BJ/QiwM8kc0xjtHA0Eyh9b0cHP2n2cdxXSIUm0/LEUgLcAuNGbMQa4A6pI1/0+cXaUbEsV3dzjfULeSMOZSz9iJv9DQmtSDbGKSUAe9Wx4t3TlIXT7aIi8DcNwizr1OhAW0MuI+Hstqvn3N+x9KHOde6eJV+UMzNGKclvY0Y8ok/XBbQ0Iec34TennQxtdxuDk4Fvbjd0/LOAMmvyHBoD0BTz02Y91NzV2zLBJUfFzCJyfsdLYgIlh+FQtTpRlhuEULU3eN7XBTy2c1nX7/lImvPufW1sp2XS6D/1alPSRKVryD2B8/ztbme4tGsQX+w2f1x4+7atwV7hrxZe6Ygg0X4Oml17vBJhj5NBiPRqUfcHw96GhJ9CqMwUhjFSXvo7Sl6hctc77UwO7VIjerXmld52xuyqD0KmlYfAj39yhBL296kIIjTzZSFMbIEd0xLQd0=
deploy:
- provider: npm
  api_key:
    secure: AlrWtqXK/zEP3B/9Dbo9xnM4TwzEzcTISNsO0Dk0W4MtyiQJQ53z8YfmLVpltAuP4d+lsmWWyNa2GBblf2/sKE+vJPuk+HYnwQhIbvLq48OLeziUKUMIB4wQiS+mVuF5MpyiBtla6JQSGvLnOFAUHEkv6df3gMamzJYXiHnFnGr+8867tb8u6OVr2q+1plCU37/3b5eaLeV5wyVZ1vqdzH+y4wVmtW2OxZSKjZ1l1b10Po3x1/vlX3CS/gmO1v2xGSgFaOPsX7ssABkT4YlgsYbZCC+LWE5D3AQvq01sifRqCDHq6k8mSflpcDU9u5YrsThn0J1cJ9zLPz8D2GU+gZ9rLILdsUad1MzAgTZ2F6O4YcFJ8efT2uWOk0RcWKoKmHYzKDKq0cWftv9FvMkLXW8L27w0nmf9LLP5HsVQu98jFflZIB182QkTM3SM8xwP3AtVLBjTe1bMbcRnqSPOkVy/+CZ4GAdYWoDgOBGFpiyQ1u/NJVrsUxcfPOB4aVqCIaG0b81StmbK9mIxuMKysSuaVAhIklaTi+8rCNzV7qov4mEDqhMzKWJSj7xztBrAO0LwKHdakhsEvqmBv18lUN3dygGVu2YKrnSgovdPQllzO/reNAcZR2uQEEOgDvSWy1+frHMQh/ZW0WixWJc8HVd62S9RKa4lXsuR2GfcPTc=
  email:
    secure: kYP8PPmyzSJE6NPqEjQKyyowzFyIkMDAOhDTH2sHVfWHLjbhZ85j5Ye0hPKuJsV3CzjHZqJS2Ew4CoB5P9N5Vl4trV493ZLOaaTsTe0M/IXXsPtbWn55B5ChZqfskvSFtrElsIq7CvClG8F0aW/UviZ3lP4cD/xj0WWk5dtfNu8NzcWXW/XAkHeGh+so5CJC7j9ujl1Gsu9f929Baw7a8EUqCHqcubK6smTYZ9BRNlM/QlNDDsbFoHy3zNJDfMYdhw/yBPCtR2aGfWlZHHfm7nwoAKkyNxudngAE2F68zLmzPuvmB6VMgxD72lpxflwpsRqLaVsVFnvTxld9tLQKoQSzCbpglbN7rnvSwxe3VMFpf0yjp862BPFWZTY9T2+SBZ0zISpRSFF/53flZcSOKkoWLQwEfHrSTjetkkN1CCGshbHQ16LLdxZkh5Ij0HmcU6kgfpXyM3+/FiR0a4tiudl4SccA6FVFLws4Yuds+w3OSckVVI31MRatfhgxJDgSrBvpWgY5npQJjlwzzhKEI1T9C2xkKf2jvr//wbpsXGFk5VXN1LdwC7iFozEJDoDqgmILrH69+f0rtgngCSQ2QhQfyQrk1wBKjS7rNsadGTZAyr67Lmdxf/NWphKozUSMrorXY+t83azlYR1gcvuYAIcOnu+463rzFqdCnlfOwZ4=
  on:
    branch: master
