language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: SoJlpkKA80hvRNTa4WMgRxrzOXZ6BZX89SKp4UIJVLNb08ze9eyU4K51Em6ZbA8oUUbZ2KVcWNe4VOO1qdX1cixwvE3CG2RhcIp8akDnrPqgl77PdIFVELNpwiZmNdv/E8AWepH150j4y6rlD1eLFjavslSl1Y5+uYW/7i9QmB2zLzwG+MBr4aDy2LPKG13n3jbZaHa2jKLlodfCwXBZpBdLuzNBG5JEP5WCJTvl7OaPyajyHfdj5CNhY+9med80aP1+8B1mkzVwzEbg9CIJcHGCPhNxSBrQY6IjoGI8+mbwW67ZdD9lcH1ql1PAwhWI0nZS9RZ5EA21k4J+yx0ly8Pm/Xd3mMriBtRYC/KGPTE8ntvufr8tRrXbg2tT+KegbgeYfYa5oxZc3gM2Zbz3QutV0xZT5F61jeKSbaNZFj2wt7OUJVlXOM/a/HxREfGA00y8CPIQ21f0LYxU4AKMMWhxEeRdOWzSYXtiusnX5mnTmCM7lAPpU2Y6sGROoYW4CAzqR3AzAgBaz6t4FSKO7upBQ+zYkJTNOTpZyRV0O2awWlXOND68dMqP+ympxXmmC85LOQY3OPJL2dJkiiMjKZJco3L26coO4Qjpbsuhwuvl4RI0AnmUvub389QrzNSwSlEu2fwSXTf9e2IZFXAgvHZdCX4tD7jrssBav7SIntU=
notifications:
  slack:
    secure: ohS1O1fJneyopOvRLTv+whGoPai/OuJFAqvNXmaLWKj13/MnP2suswlzXbVvpZfzsUbaNovPCX0poBPMw0aJTioKrmkGIklo5502+fisqqZDISHi5DG73LX0g71u7f2afayuXh2SqG1eyyNTwHpFuRXALmRhuLblsrjYGgXjbaU5j0J269HBF33WsVzPjNN04PAc183iobZVL9h8h0MezbIcfT8ZnQBGVRrrrhLArb3jmJMFxYju1Y2aBXL1mxtAejlCycUi272EcnTyCOTAAJT7oy3AEzWHcKnKlj4q5EHPA6aSFbkGTOSMrlD0n0PdGEV/vHtdyZIOiEv4VG0IkTnYJuTUCuZ3/FKA9TUIMBIujSYcBUsQW5eGOez9p1TyyASoaeeG3fXVeKlis9oyg7ChgV505t9jG2Z4kaNxb6z0jEEIwGc6+uq7ZouZiLU/wdK3hJjz1/KtycuHg9OezEM3Fw4eMZ4LWEMf4a0S6ubAR2hdmhzN/aH8VYLAeRAE7n19HN9FT3Uk2SVW7cA+/b//9Ck/K4/ocxy4boPWe/BA26sWfKuwkXjqAOh0OyXTu2WK64mcGwv46BID0DChGyKVNZtHC8IH+0jL//VtPwSC7bgTWTve40dFSEwGN2z0U9G+rf0csmeJZzhKWC6RVFUh1Evs+rBtlV4SJgaa79U=
