language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: hCdbRoU4JZCgT5oKRTtzjVzC8mcUljGihZbywtfcrYD/nwPx36zz1zBNkVjn6GlHiJ3aOeBoryj6CekV23TvqhiVO2oxOc0Ztl+Hqpf6gUms3mSct4PSd1HQo5tKI5uyji8TVausMSU2N455hf2sd4C80qrEtO8QDmxnCgkRBK9KD1kEQ/Yqh57i60pp+8RP98gCl26RODCubLXvpI+J+oGZ6Du8gV7Xr1qm7Mnm6t2t/JKkWQASzmo05Yitgzotf+B+lY8JVmS/+nY3vvRHnkhf3DhRfFz9+zarxighCDekdJOGF1/WW1KL1iM+ArbYyjWuZMC0PQaIRgc7JxjgA0VUKwPg0iAh2UGp+/5606s2Pi8d0zV+vh7/Vt52tUgXj25beqn66RxwQT+iJsTe71ajJIbt9SRbSZUO4F9IqmDP8t6gaBjrfvbkcPdEgPanwgH5+2bViJrI537iF+Y7n/Ggptb6lk2ohF+fnHr8qDvlTXzbENvgi+i8PzlIp3jmhpgfQHVBWJfFVTfwNU0e+zKp+CsvH7Vz19zxra4BchH9xw5/7Jj1bvvxvqxd5pleMSPAZ5Uy6yJ7QUJKRCgE2D2ikZ+Z1J5sm/Uxmq3WNghcfYsyPNPrAjzwMNICQiHpR+21c+IbjTk7m0IXXd6dt9GHiV7h7DjVxisleOa3Lng=
notifications:
  slack:
    secure: fK5ec8CF7vjfivY3MGNNisewuYfoJzC4AO3ErINcR28J35gdYLDNcvw9pUM/5aJ/NNcYKQ1HnkwAHyLzl04nHz7MzALnTB+3d5yUd+mt/1abBcUcBU7DehsKhXKBrXlls5PqhVYjEe0sNGjfp3ZSALvBPY5j2F/y5kCNSZKyGlYoc6qceFHF+v58fxifr22xqdH8HbmTJKENuy2NatxYoKLAyxf2yMM5t1EmLNGzf88w6+SaVT4iI93FUcKdm3g4mf9o5ypRQ5ajbApIQ1EUEV/V/pl6COckyZKMI2u04wIPg94m2q6rjkaHXF8AdQM7Q8p1q8LO8wqO+tj8RjXehe5qc5QRqbPB7PmAnEwKZ+uFFolPJiO0ySOKYzp4QcvldbUt10O3nVZgF5pg3G9wBkOm4EScc99Yanam32nj6vOC/JDi+7wzo1nru3ajNM3uYkU+vdTRIfofjq4DmdzZUTyxqOCtHQEw/qvIEHm+0qTHII8VpeONL8PCA1Zm4vI79t3oBC8gmD2ZgZAKisBApr27zTpno5yI40zRuWAFefTqSBMBBoZL0SgFD1gMI19Q89x+lKARscdhYLL5DvK9RTrRQYQ8JS/P5r3WyLidLWI7K6QiDWf5eYeqqqz+iHWnQTXM7kz0/YXNvAmPsqNEh7/IjVkqWAmEIxmVZLq7ZCE=
deploy:
- provider: npm
  api_key:
    secure: gstFsPmNK5Tx/Ecbv9p0jCmouu47P/+EfDM16VNxJjqWIE+AIq+jg24qyNadZO/zzqfjs6DgnEPWQ+3ivWPxypiDjBtH8tiDEo2e/TSR+93B69IQy8enpNKvhjiObpqsZBVdjkknXiHZ9IC2EWs5u6t97m6cte+aQbb75E+0YfjiDW21ZhzdSJk7ZrnIfHUsjoqZssW3Y0FevS9Rt6ZpfXSwnZzWAba8uVkj+Iv+nsA7FRAUm3mFwyxGelmEIVbEKPe+R48yXuP51OEC64Q9kFWTFZZqtrURjVPvQy5mD02KWIdcEzw5pMzCO1X2MVkh78ccnM/kwZDMaobFSeBIX3CvyumRksPFQqOGuknBoPd9j7L+eQVLSZCJu6ySVN/i7e3ovj2fjkEnwrvqfTtHqXy8LYknNA8XcQiYfQAntePprJef5Cj9Aok+gBc0YAvLucInbgLgwxGL6RxTctovkgyX6N6/GVDNaQbvYhofhCRXY+J7evBC+IZ3EKcNhkM57SNKvCZPyu9lOCOMcMJUhAs3okkUKBPtx9cBV79aUiZeGhy7/83fR06FQ0u2b+QbA2Ke1u3CNkYpkgX4myJohiahDv21j7EOcCSzzBEKUDLhSA6/5eclYzMzl4gOy6Yqksa9ILFXSeJbZsYMxTOiwGycHAuRC4XjmEZA1O8xSps=
  email:
    secure: B8Cp9XnGJrbvJEuZc0HViS4g1ZB+D1Pc1/rp6gpwRgEGRsMD0t/7xjEQdJDamrRBY3ACsf49GAICg4Qsh+6q4PCMAC6D2KZf6jrWPzoL3YBSzt2nM+wue8USnEvlgoRJ01rZH7iitgRlUVzqqPY9Kgvm7WrAS7PrP+nYx26NONY9fc6LlOtA7JGOhllcUBxI/JRDEEUhkfUQZKz/Cj7yeaolLvUzB32O1lrCtRDWlLE1HjHnnkypiyoZBg3MdV6C7yb5Zqg3aZxpViHGF6cyOZ9gN+aZweIC+P6CycZWDWjfz0CnU+dpoU0AtXk3vzqxdMBGWPcPG/ILDh9pUh9fD6TnMmEmGKvYSCQlw57/XgQCvrfP+XyuUO6vawJd/xYzI0dBSGhNgqonXwsu4WMybsd3ZCAZ6Ebu6iwpYrJyyEcHz6IWYa/TMJcarRHgv96PYwCbSNEQZ750kpWNMWBZxj35x2gCAQ3SyHhH8TsdQ5Uu1qoX4vL3WEX7w1Tap5Td3g7R6wlCjsJ2jYvGTjTaCbY3DrQJSLaLdp5eZb5VqR2QH1L+VgT5za0Ia6JIief2H8gi2RVJ1355neu+RKPo8jFJ5YiVRsTOSl2JMK1GKncqTEQACEG160M/p1FiOwGHF8qWcYLbZ8jYBquVfv+HmmOzZO7xnUEEDSTpGpIlcKs=
  on:
    branch: master
