language: node_js
node_js:
- node
services:
- redis-server
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: SoJlpkKA80hvRNTa4WMgRxrzOXZ6BZX89SKp4UIJVLNb08ze9eyU4K51Em6ZbA8oUUbZ2KVcWNe4VOO1qdX1cixwvE3CG2RhcIp8akDnrPqgl77PdIFVELNpwiZmNdv/E8AWepH150j4y6rlD1eLFjavslSl1Y5+uYW/7i9QmB2zLzwG+MBr4aDy2LPKG13n3jbZaHa2jKLlodfCwXBZpBdLuzNBG5JEP5WCJTvl7OaPyajyHfdj5CNhY+9med80aP1+8B1mkzVwzEbg9CIJcHGCPhNxSBrQY6IjoGI8+mbwW67ZdD9lcH1ql1PAwhWI0nZS9RZ5EA21k4J+yx0ly8Pm/Xd3mMriBtRYC/KGPTE8ntvufr8tRrXbg2tT+KegbgeYfYa5oxZc3gM2Zbz3QutV0xZT5F61jeKSbaNZFj2wt7OUJVlXOM/a/HxREfGA00y8CPIQ21f0LYxU4AKMMWhxEeRdOWzSYXtiusnX5mnTmCM7lAPpU2Y6sGROoYW4CAzqR3AzAgBaz6t4FSKO7upBQ+zYkJTNOTpZyRV0O2awWlXOND68dMqP+ympxXmmC85LOQY3OPJL2dJkiiMjKZJco3L26coO4Qjpbsuhwuvl4RI0AnmUvub389QrzNSwSlEu2fwSXTf9e2IZFXAgvHZdCX4tD7jrssBav7SIntU=
